### PR TITLE
Add SparklePulse animation

### PR DESCRIPTION
**Pull request by dmolavi**
This new animation is a combo of the Sparkle and Pulse. The effect makes the Pulse work on a single pixel at a time, vs the entire set of pixels.

### CODE REVIEW

**Comment by ladyada** [comment]
@rhooper - you can also review if you like!

**Comment by rhooper** [comment]
@dmolavi I like the idea of making sparkle able to use pulse animations.  Thank you for your contribution!  There seems to be a lot of duplication and/or unused code from Sparkle and Pulse that can be cleaned up.  I will look closer later today, and suggest the changes needed.

**Comment by dmolavi** [comment]
You're more than welcome. This was quick and dirty to get it up and running. I'm more than open to modularizing some of the common code between the animations or whatever other changes should be made.

**Comment by rhooper** [comment]
I should mention an outstanding PR with a whole bunch of changes and improvements that could make the cleanup suggested easier.

I just pushed a refactor to that PR that moved the pulse generator to helper.py
https://github.com/adafruit/Adafruit_CircuitPython_LED_Animation/pull/10/files#diff-4b2c1e050cf3860b0985abfb719ca2b9R212
https://github.com/adafruit/Adafruit_CircuitPython_LED_Animation/pull/10/files#diff-64b1eba82bd2cf60853e11d3c2bbb9b1R386

**Comment by dmolavi** [comment]
@rhooper - I don't want to step on toes, so I haven't pushed this PR any further, esp if you have a refactor and new stuff coming in with your PR.  I'm wondering if maybe merging the two PRs into one might be the best solution here?

**Comment by kattni** [comment]
There's no ETA on the refactor. I will merge this as is and we will do the necessary/requested cleanup at a later date.

**Pull request merged**
