### PR TITLE
Fixed reverse mode for Comet / RainbowComet animation.

### PR DESCRIPTION
**Pull request by plugowski**
In this commit I fixed reverse mode for Comet animations. Also attribute setters and getters has been added to have an option to dynamically modify current working animation.

### CODE REVIEW

**Comment by jposada202020** [comment]
@plugowski could you take a look in the link below. This could help making the CI pass the tests. We could review this PR after that.  Thanks
Instructions are available here: https://adafru.it/check-your-code

**Comment by plugowski** [comment]
@jposada202020 okay I added pre-commit and commited fixed file.

**Comment by jposada202020** [comment]
Thanks @plugowski .
@kattni this one is ready also for review, now I guess we wait on the decision regarding the animations :)
Thanks

**Comment by rhooper** [comment]
This looks good to me, @kattni

**Review by kattni — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
