### PR TITLE
Add more animations, add AggregatePixels helper.

### PR DESCRIPTION
**Pull request by rhooper**
Add more animations, add AggregatePixels helper, add names to animations, add random order, add cycle done callback.

### CODE REVIEW

**Comment by kattni** [comment]
Needs documentation improvements, and testing without pixelbuf (potentially on Raspberry Pi).

**Comment by rhooper** [comment]
@kattni I don't know how to resolve this error... Some help would be great.

```
Warning, treated as error:
/home/runner/work/Adafruit_CircuitPython_LED_Animation/Adafruit_CircuitPython_LED_Animation/docs/index.rst:17:toctree contains reference to document 'api' that doesn't have a title: no link will be generated
##[error]Process completed with exit code 2.
```

**Comment by siddacious** [comment]
@rhooper @kattni What's the status of this? Looks like it needs to be rebased or otherwise synched, but is this good to go otherwise?

**Comment by kattni** [comment]
@siddacious There is a significant amount of cleanup needed, not including the rebase, before it can be merged. It was waiting on all of the other pixel stuff to be settled which only happened yesterday. Limor asked that I wait to do anything with it until all of that was taken care of, and obviously the situation changed in the meantime. Please leave this open for now.

**Review by FoamyGuy — APPROVED** [review]
I tested the all 3 examples successfully on a Pybadge, a Circuit Playground Bluefruit and a RasPi 3 B+. 

`led_animation_simpletest.py` works on Metro M0 Express but he other two examples have memory error. 

One minor issue on the Rasperry Pi 3 B+ the `rainbow_comet` animations was not working on that device for me. No errors or anything, pixels all stayed off during that animation. 

One minor suggestion: slow down default speed for the the blink animation in the `led_animation_all_animations.py` so it's not flashing so fast out of the gate. 

I don't think either are major enough to block merging though.

Thank you Roy and Kattni for working on this very cool library!

**Pull request merged**
